<?php

$pegawai = array(
    "",
    "Dr. ILHAM CHAIDIR",
    "Dr. YOHANA MARI YUSTINI",
    "Drg. MELLYAWATI",
    "Dr. DINDIN A. SETIAWATY",
    "Dr. LINA RUFLINA",
    "Drg. SITI MILYARNI REMIKA, MM",
    "ROSMIATI",
    "SADIYAH, AMKG",
    "Drg. KARINA AMALIA",
    "SUGIHARYATI, AMKeb",
    "HUSNA",
    "ENENG SURTININGSIH, AMKep",
    "ENDAH PURASANTI, AMKeb",
    "DWIJO KURJIANTO, AMAK",
    "SEPTY MARHAENY, AMKep",
    "FEBBY HENDRIYANI  S.",
    "NINA ANDRIYANTI, AMKL",
    "RIDWANUDIN HARIS, AMKep",
    "MARICE SINORITA, AMKeb",
    "T A R P I N, AMRad",
    "MARYANI, A.Md Kp",
    "IIS AISAH",
    "MAD SOLEH",
    "AGTI NURVITASARI, SKM",
    "NIDA NURAIDA, AMdG"
);
?>
